# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltag',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalTag',
        ),
    ]
