---
- hosts: all
  vars:
    mode: development
    stashuser: amcpherson
    stashversion: master
    gitexecutable: git
  tasks:
    - name: Clone tantalus repo
      environment:
        GIT_SSL_NO_VERIFY: true
      git:
        repo: "https://{{ stashuser | urlencode }}:{{ stashpassword }}@svn.bcgsc.ca/bitbucket/scm/sc/tantalus.git"
        dest: $HOME/{{ mode }}/{{ queue_prefix }}/tantalus
        version: "{{ stashversion }}"
        executable: "{{ gitexecutable }}"
      tags:
        - backend

    - name: Install requirements
      pip:
        requirements: $HOME/{{ mode }}/{{ queue_prefix }}/tantalus/requirements.txt
        virtualenv: $HOME/{{ mode }}/{{ queue_prefix }}/tantalus/venv

    - name: Create supervisor tmp
      file: path=$HOME/{{ mode }}/{{ queue_prefix }}/tantalus/tmp state=directory

    - name: Create supervisor tmp/logs
      file: path=$HOME/{{ mode }}/{{ queue_prefix }}/tantalus/tmp/logs state=directory

    - name: Stop celery
      shell: "$HOME/{{ mode }}/{{ queue_prefix }}/tantalus/venv/bin/supervisorctl -c $HOME/{{ mode }}/{{ queue_prefix }}/tantalus/supervisord.conf stop all"
      tags: shutdown

    - name: Stop supervisord
      shell: "if [ -f $HOME/{{ mode }}/{{ queue_prefix }}/tantalus/tmp/supervisord.pid ]; then kill -15 $($HOME/{{ mode }}/{{ queue_prefix }}/tantalus/venv/bin/supervisorctl -c $HOME/{{ mode }}/{{ queue_prefix }}/tantalus/supervisord.conf pid); fi; sleep 10"
      tags: shutdown

    - name: Start supervisord
      shell: "$HOME/{{ mode }}/{{ queue_prefix }}/tantalus/venv/bin/supervisord -c $HOME/{{ mode }}/{{ queue_prefix }}/tantalus/supervisord.conf"
      environment:
        TANTALUS_QUEUE_PREFIX: "{{ queue_prefix }}"
        TANTALUS_SECRET_KEY: "{{ lookup('env', 'TANTALUS_SECRET_KEY') }}"
        TANTALUS_DEBUG: "{{ lookup('env', 'TANTALUS_DEBUG') }}"
        TANTALUS_IS_PRODUCTION: "{{ lookup('env', 'TANTALUS_IS_PRODUCTION') }}"
        TANTALUS_POSTGRESQL_NAME: "{{ lookup('env', 'TANTALUS_POSTGRESQL_NAME') }}"
        TANTALUS_POSTGRESQL_USER: "{{ lookup('env', 'TANTALUS_POSTGRESQL_USER') }}"
        TANTALUS_POSTGRESQL_PASSWORD: "{{ lookup('env', 'TANTALUS_POSTGRESQL_PASSWORD') }}"
        TANTALUS_RABBIT_USER: "{{ lookup('env', 'TANTALUS_RABBIT_USER') }}"
        TANTALUS_RABBIT_PASSWORD: "{{ lookup('env', 'TANTALUS_RABBIT_PASSWORD') }}"
        TANTALUS_RABBIT_VHOST: "{{ lookup('env', 'TANTALUS_RABBIT_VHOST') }}"
        TANTALUS_RABBIT_IP: "{{ lookup('env', 'TANTALUS_RABBIT_IP') }}"
        GSC_API_URL: "{{ lookup('env', 'GSC_API_URL') }}"
        GSC_API_USERNAME: "{{ lookup('env', 'GSC_API_USERNAME') }}"
        GSC_API_PASSWORD: "'{{ lookup('env', 'GSC_API_PASSWORD') }}'"
        TASK_LOG_USERNAME: "'{{ lookup('env', 'TASK_LOG_USERNAME') }}'"
        TASK_LOG_HOSTNAME: "'{{ lookup('env', 'TASK_LOG_HOSTNAME') }}'"
        TASK_LOG_DIRECTORY: "'{{ lookup('env', 'TASK_LOG_DIRECTORY') }}'"
        COLOSSUS_API_URL: "'{{ lookup('env', 'COLOSSUS_API_URL') }}'"

