---
- hosts: all
  remote_user: amcpherson
  tasks:
    - name: Clone tantalus repo
      git:
        repo: "https://{{ githubuser | urlencode }}:{{ githubpassword }}@svn.bcgsc.ca/bitbucket/scm/sc/tantalus.git"
        dest: $HOME/production/tantalus

    - name: Install requirements
      pip:
        requirements: $HOME/production/tantalus/requirements.txt
        virtualenv: $HOME/production/tantalus/venv
        virtualenv_python: python2

    - name: Start supervisord
      shell: "if [ ! -S $HOME/production/tantalus/tmp/supervisor.sock ]; then $HOME/production/tantalus/venv/bin/supervisord -c $HOME/production/tantalus/supervisord.conf; fi"
      environment:
        TANTALUS_SECRET_KEY: "{{ lookup('env', 'TANTALUS_SECRET_KEY') }}"
        TANTALUS_DEBUG: "{{ lookup('env', 'TANTALUS_DEBUG') }}"
        TANTALUS_POSTGRESQL_NAME: "{{ lookup('env', 'TANTALUS_POSTGRESQL_NAME') }}"
        TANTALUS_POSTGRESQL_USER: "{{ lookup('env', 'TANTALUS_POSTGRESQL_USER') }}"
        TANTALUS_POSTGRESQL_PASSWORD: "{{ lookup('env', 'TANTALUS_POSTGRESQL_PASSWORD') }}"

    - name: Start celery
      supervisorctl:
        name: celeryd
        state: restarted
        config: $HOME/production/tantalus/supervisord.conf
        supervisorctl_path: $HOME/production/tantalus/venv/bin/supervisorctl

