version: '2.1'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_USER=amcpherson
        - POSTGRES_PASSWORD=shahlab
        - POSTGRES_DB=tantalus_dev
      ports:
        - '5432:5432'
      healthcheck:
        test: ["CMD", "curl", "-f", "http://db:5432"]
        interval: 30s
        timeout: 10s
        retries: 2

    django:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: tantalus
      image: docker_tantalus
      stdin_open: true
      tty: true
      command: ["python", "manage.py", "runserver", "8000"]
      volumes:
        - .:/tantalus
      ports:
        - "8000:8000"
      depends_on:
        - db

