version: '2.1'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_USER=simong
        - POSTGRES_PASSWORD=pinchpinch
        - POSTGRES_DB=tantalus_dev
      healthcheck:
        test: ["CMD", "curl", "-f", "http://db:5432"]
        interval: 30s
        timeout: 10s
        retries: 2

    django:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: tantalus
      image: docker_tantalus
      stdin_open: true
      tty: true
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuserargs --username simong --password pinchpinch --noinput --email 'simong@crab.com' && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/tantalus
      ports:
        - "8000:8000"
      depends_on:
        - db

