# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
