# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='files',
            new_name='datasets',
        ),
    ]
