# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='datasets',
            field=models.ManyToManyField(to='tantalus.SequenceDataset'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='file_transfers',
            field=models.ManyToManyField(to='tantalus.FileTransfer'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='from_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_storage', to='tantalus.Storage'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='to_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_storage', to='tantalus.Storage'),
        ),
        migrations.AlterField(
            model_name='singleendfastqfile',
            name='reads_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.SequenceDataFile'),
        ),
    ]
