# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 21:31
from __future__ import unicode_literals

from django.db import migrations


def add_storages(apps, schema_editor):
    ServerStorage = apps.get_model('tantalus', 'ServerStorage')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    server_storage_ctype = ContentType.objects.get_for_model(ServerStorage)

    storage = ServerStorage()
    storage.name = 'rocks'
    storage.server_ip = '10.9.2.187'
    storage.storage_directory = '/share/lustre/archive'
    storage.username = 'amcpherson'
    storage.polymorphic_ctype = server_storage_ctype
    storage.save()

    storage = ServerStorage()
    storage.name = 'gsc'
    storage.server_ip = '10.9.208.161'
    storage.storage_directory = '/'
    storage.username = 'amcpherson'
    storage.polymorphic_ctype = server_storage_ctype
    storage.save()

    storage = ServerStorage()
    storage.name = 'shahlab'
    storage.server_ip = '10.9.208.161'
    storage.storage_directory = '/shahlab/archive'
    storage.username = 'amcpherson'
    storage.polymorphic_ctype = server_storage_ctype
    storage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_storages),
    ]
