# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0002_auto_20171020_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserverstorage',
            name='queue_prefix',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverstorage',
            name='queue_prefix',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
