# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 22:45
from __future__ import unicode_literals

from django.db import migrations


def add_storage_queue_prefix(apps, schema_editor):
    ServerStorage = apps.get_model('tantalus', 'ServerStorage')

    s = ServerStorage.objects.get(name='rocks')
    s.queue_prefix = 'rocks'
    s.save()

    s = ServerStorage.objects.get(name='gsc')
    s.queue_prefix = 'gsc'
    s.save()

    s = ServerStorage.objects.get(name='shahlab')
    s.queue_prefix = 'gsc'
    s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0003_auto_20171020_2244'),
    ]

    operations = [
        migrations.RunPython(add_storage_queue_prefix),
    ]
