# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0004_auto_20171020_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryGscDlpPairedFastqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('state', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('dlp_library_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryGscWgsBams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('state', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.Sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='gscquery',
            name='samples',
        ),
        migrations.DeleteModel(
            name='GSCQuery',
        ),
    ]
