# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0005_auto_20171026_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsequencelane',
            name='lane_number',
            field=models.CharField(blank=True, choices=[('', ''), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sequencelane',
            name='lane_number',
            field=models.CharField(blank=True, choices=[('', ''), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9')], max_length=50),
        ),
    ]
