# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tantalus', '0007_auto_20171031_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureBlobCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAzureBlobCredentials',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical azure blob credentials',
            },
        ),
        migrations.RemoveField(
            model_name='azureblobstorage',
            name='storage_key',
        ),
        migrations.RemoveField(
            model_name='historicalazureblobstorage',
            name='storage_key',
        ),
        migrations.AddField(
            model_name='azureblobstorage',
            name='credentials',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tantalus.AzureBlobCredentials'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalazureblobstorage',
            name='credentials',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tantalus.AzureBlobCredentials'),
        ),
    ]
