# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0008_auto_20171031_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRCImportFastqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('state', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('output_dir', models.CharField(max_length=500)),
                ('flowcell_id', models.CharField(max_length=50)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='tantalus.Storage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
