# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0009_brcimportfastqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsample',
            name='sample_id_space',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_id_space',
        ),
        migrations.AlterField(
            model_name='brcimportfastqs',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.ServerStorage'),
        ),
    ]
