# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0010_auto_20171102_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
