# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 23:56
from __future__ import unicode_literals

from django.db import migrations


def set_deployment_name(apps, schema_editor):
    Deployment = apps.get_model('tantalus', 'Deployment')
    for idx, deployment in enumerate(Deployment.objects.all()):
        deployment.name = 'deployment_{}'.format(idx)
        deployment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0011_deployment_name'),
    ]

    operations = [
        migrations.RunPython(set_deployment_name)
    ]

