# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0012_auto_20171108_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(default='unused', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
