# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0013_auto_20171109_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BRCImportFastqs',
            new_name='BRCFastqImport',
        ),
        migrations.RenameModel(
            old_name='QueryGscDlpPairedFastqs',
            new_name='GscDlpPairedFastqQuery',
        ),
        migrations.RenameModel(
            old_name='QueryGscWgsBams',
            new_name='GscWgsBamQuery',
        ),
    ]
