# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0016_deployment_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='start',
        ),
    ]
