# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0017_remove_deployment_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractdataset',
            name='tags',
        ),
    ]
