# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0019_auto_20171208_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='datasets',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='file_transfers',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='from_storage',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='to_storage',
        ),
        migrations.AlterUniqueTogether(
            name='filetransfer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='filetransfer',
            name='file_instance',
        ),
        migrations.RemoveField(
            model_name='filetransfer',
            name='from_storage',
        ),
        migrations.RemoveField(
            model_name='filetransfer',
            name='to_storage',
        ),
        migrations.DeleteModel(
            name='Deployment',
        ),
        migrations.DeleteModel(
            name='FileTransfer',
        ),
    ]
