# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0020_auto_20171208_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('state', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tag_name', models.CharField(max_length=50)),
                ('from_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filetransfer_from_storage', to='tantalus.Storage')),
                ('to_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filetransfer_to_storage', to='tantalus.Storage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservedFileInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.FileResource')),
                ('file_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.FileTransfer')),
                ('to_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.Storage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reservedfileinstance',
            unique_together=set([('file_resource', 'to_storage')]),
        ),
    ]
