# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0021_auto_20171208_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='gscdlppairedfastqquery',
            name='gsc_library_id',
            field=models.CharField(default='invalid', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
