# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0029_auto_20180206_2114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dnasequences',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dnasequences',
            name='dna_library',
        ),
        migrations.RemoveField(
            model_name='dnasequences',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='historicaldnasequences',
            name='dna_library',
        ),
        migrations.RemoveField(
            model_name='historicaldnasequences',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldnasequences',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='abstractdataset',
            name='dna_sequences',
        ),
        migrations.RemoveField(
            model_name='abstractdataset',
            name='lanes',
        ),
        migrations.RemoveField(
            model_name='historicalabstractdataset',
            name='dna_sequences',
        ),
        migrations.RemoveField(
            model_name='historicalbamfile',
            name='dna_sequences',
        ),
        migrations.RemoveField(
            model_name='historicalbclfolder',
            name='dna_sequences',
        ),
        migrations.RemoveField(
            model_name='historicalpairedendfastqfiles',
            name='dna_sequences',
        ),
        migrations.RemoveField(
            model_name='historicalsingleendfastqfile',
            name='dna_sequences',
        ),
        migrations.DeleteModel(
            name='DNASequences',
        ),
        migrations.DeleteModel(
            name='HistoricalDNASequences',
        ),
        migrations.RemoveField(
            model_name='historicalsequencelane',
            name='dna_library',
        ),
        migrations.RemoveField(
            model_name='sequencelane',
            name='dna_library',
        ),
    ]
