# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0030_auto_20180206_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreadgroup',
            name='sequencing_library_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='readgroup',
            name='sequencing_library_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
