# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 20:01
from __future__ import unicode_literals

from django.db import migrations


def move_sequencing_library_id(apps, schema_editor):
    ReadGroup = apps.get_model('tantalus', 'ReadGroup')

    for r in ReadGroup.objects.all():
        r.sequencing_library_id = r.sequence_lane.sequencing_library_id
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0031_auto_20180209_2001'),
    ]

    operations = [
        migrations.RunPython(move_sequencing_library_id)
    ]
