# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0032_auto_20180209_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsequencelane',
            name='sequencing_library_id',
        ),
        migrations.RemoveField(
            model_name='sequencelane',
            name='sequencing_library_id',
        ),
    ]
