# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import tantalus

def populate_file_resources(apps, schema_editor):
    
    for b in tantalus.models.BCLFolder.objects.all():
        b.file_resources.add(b.folder)

    for b in tantalus.models.SingleEndFastqFile.objects.all():
        b.file_resources.add(b.reads_file)

    for b in tantalus.models.PairedEndFastqFiles.objects.all():
        b.file_resources.add(b.reads_1_file)
        b.file_resources.add(b.reads_2_file)

    for b in tantalus.models.BamFile.objects.all():
        b.file_resources.add(b.bam_file)
        if b.bam_index_file is not None:
            b.file_resources.add(b.bam_index_file)

class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0034_auto_20180218_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractdataset',
            name='file_resources',
            field=models.ManyToManyField(blank=True, to='tantalus.FileResource'),
        ),
        migrations.RunPython(populate_file_resources),
    ]
