# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0035_abstractdataset_file_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brcfastqimport',
            name='message',
        ),
        migrations.RemoveField(
            model_name='filetransfer',
            name='message',
        ),
        migrations.RemoveField(
            model_name='gscdlppairedfastqquery',
            name='message',
        ),
        migrations.RemoveField(
            model_name='gscwgsbamquery',
            name='message',
        ),
        migrations.RemoveField(
            model_name='md5check',
            name='message',
        ),
    ]
