# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0036_auto_20180326_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='brcfastqimport',
            name='stopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='stopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gscdlppairedfastqquery',
            name='stopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gscwgsbamquery',
            name='stopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='md5check',
            name='stopping',
            field=models.BooleanField(default=False),
        ),
    ]
