# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 23:27
from __future__ import unicode_literals

from django.db import migrations, models

from tantalus.models import FileResource


def fix_bai_file_type(apps, schema_editor): 
    file_resources = FileResource.objects.all().filter(filename__icontains='.bai', file_type='BAM')
    for file_resource in file_resources:
        file_resource.file_type = 'BAI'
        file_resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0037_auto_20180328_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bamfile',
            name='reference_genome',
            field=models.CharField(default='UNALIGNED', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalbamfile',
            name='reference_genome',
            field=models.CharField(default='UNALIGNED', max_length=50),
        ),
        migrations.RunPython(fix_bai_file_type),
    ]
