# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 22:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0038_auto_20180418_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDlpBam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('stopping', models.BooleanField(default=False)),
                ('state', models.TextField(blank=True)),
                ('bam_paths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.Storage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
