# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0041_auto_20180524_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureblobstorage',
            name='storage_account',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='azureblobstorage',
            name='storage_container',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='historicalazureblobstorage',
            name='storage_account',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='historicalazureblobstorage',
            name='storage_container',
            field=models.CharField(max_length=63),
        ),
    ]
