# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0043_auto_20180530_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='gscwgsbamquery',
            name='skip_file_import',
            field=models.BooleanField(default=False),
        ),
    ]
