# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0044_gscwgsbamquery_skip_file_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='generictasktype',
            name='description',
            field=models.TextField(blank=True, help_text=b'A description of the task.', max_length=50, null=True),
        ),
    ]
