# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-08 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0045_generictasktype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsample',
            name='tissue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tissue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
