# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0046_auto_20180608_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='compression',
            field=models.CharField(choices=[('GZIP', 'gzip'), ('BZIP2', 'bzip2'), ('SPEC', 'SpEC'), ('UNCOMPRESSED', 'uncompressed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalfileresource',
            name='compression',
            field=models.CharField(choices=[('GZIP', 'gzip'), ('BZIP2', 'bzip2'), ('SPEC', 'SpEC'), ('UNCOMPRESSED', 'uncompressed')], max_length=50),
        ),
    ]
