# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0048_gscwgsbamquery_skip_older_than'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictasktype',
            name='description',
            field=models.TextField(blank=True, help_text=b'A description of the task.', null=True),
        ),
    ]
