# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0049_auto_20180614_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsequencelane',
            name='sequencing_instrument',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sequencelane',
            name='sequencing_instrument',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
