# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tantalus', '0050_auto_20180706_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSequenceDataset',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('dataset_type', models.CharField(choices=[('BAM', 'BAM Files'), ('FQ', 'FastQ Files')], default='BAM', max_length=50)),
                ('reference_genome', models.CharField(choices=[('HG19', 'Human Genome 19'), ('HG18', 'Human Genome 18'), ('UNALIGNED', 'Not aligned to a reference'), ('UNUSABLE', 'Alignments are not usable')], default='UNALIGNED', max_length=50)),
                ('aligner', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tantalus.DNALibrary')),
                ('sample', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tantalus.Sample')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical sequence dataset',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSequencingLane',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('flowcell_id', models.CharField(max_length=50)),
                ('lane_number', models.CharField(blank=True, choices=[('', ''), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9')], max_length=50)),
                ('sequencing_centre', models.CharField(choices=[('GSC', 'Genome Science Centre'), ('BRC', 'Biomedical Research Centre')], max_length=50)),
                ('sequencing_instrument', models.CharField(blank=True, max_length=50, null=True)),
                ('sequencing_library_id', models.CharField(max_length=50, null=True)),
                ('read_type', models.CharField(choices=[('P', 'Paired end tags'), ('S', 'Single end tags')], max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dna_library', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tantalus.DNALibrary')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical sequencing lane',
            },
        ),
        migrations.CreateModel(
            name='SequenceDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dataset_type', models.CharField(choices=[('BAM', 'BAM Files'), ('FQ', 'FastQ Files')], default='BAM', max_length=50)),
                ('reference_genome', models.CharField(choices=[('HG19', 'Human Genome 19'), ('HG18', 'Human Genome 18'), ('UNALIGNED', 'Not aligned to a reference'), ('UNUSABLE', 'Alignments are not usable')], default='UNALIGNED', max_length=50)),
                ('aligner', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingLane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowcell_id', models.CharField(max_length=50)),
                ('lane_number', models.CharField(blank=True, choices=[('', ''), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9')], max_length=50)),
                ('sequencing_centre', models.CharField(choices=[('GSC', 'Genome Science Centre'), ('BRC', 'Biomedical Research Centre')], max_length=50)),
                ('sequencing_instrument', models.CharField(blank=True, max_length=50, null=True)),
                ('sequencing_library_id', models.CharField(max_length=50, null=True)),
                ('read_type', models.CharField(choices=[('P', 'Paired end tags'), ('S', 'Single end tags')], max_length=50)),
                ('dna_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.DNALibrary')),
            ],
        ),
        migrations.AddField(
            model_name='fileresource',
            name='genome_region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='index_sequence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalfileresource',
            name='genome_region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalfileresource',
            name='index_sequence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='file_resources',
            field=models.ManyToManyField(to='tantalus.FileResource'),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.DNALibrary'),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.Sample'),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='sequence_lanes',
            field=models.ManyToManyField(to='tantalus.SequencingLane'),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='tags',
            field=models.ManyToManyField(to='tantalus.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencinglane',
            unique_together=set([('flowcell_id', 'lane_number', 'dna_library')]),
        ),
    ]
