# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0055_auto_20180807_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransfer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
