# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0056_auto_20180808_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='gscwgsbamquery',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
