# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0059_auto_20180810_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='genome_region',
        ),
        migrations.RemoveField(
            model_name='fileresource',
            name='index_sequence',
        ),
        migrations.RemoveField(
            model_name='fileresource',
            name='read_end',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='genome_region',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='index_sequence',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='read_end',
        ),
    ]
