# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0061_auto_20180813_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='tags',
            field=models.ManyToManyField(to='tantalus.Tag'),
        ),
        migrations.AddField(
            model_name='resultsdataset',
            name='tags',
            field=models.ManyToManyField(to='tantalus.Tag'),
        ),
    ]
