# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0062_auto_20180814_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='input_datasets',
            field=models.ManyToManyField(blank=True, related_name='inputdatasets', to='tantalus.SequenceDataset'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='input_results',
            field=models.ManyToManyField(blank=True, related_name='inputresults', to='tantalus.ResultsDataset'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='logs',
            field=models.ManyToManyField(blank=True, to='tantalus.FileResource'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tantalus.Tag'),
        ),
    ]
