# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0065_auto_20180910_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='file_type',
        ),
    ]
