# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0066_auto_20180910_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileresource',
            old_name='file_type2',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='historicalfileresource',
            old_name='file_type2',
            new_name='file_type',
        ),
    ]
