# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-12 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0067_auto_20180910_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsdataset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tantalus.Tag'),
        ),
    ]
