# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0068_auto_20180912_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencedataset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tantalus.Tag'),
        ),
    ]
