# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-19 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0069_auto_20181004_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='projects',
            field=models.ManyToManyField(null=True, to='tantalus.Project'),
        ),
    ]
