# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0070_auto_20181019_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsequencedataset',
            name='reference_genome',
            field=models.CharField(choices=[('HG19', 'Human Genome 19'), ('HG18', 'Human Genome 18'), ('MM10', 'Mouse Genome 10'), ('UNALIGNED', 'Not aligned to a reference'), ('UNUSABLE', 'Alignments are not usable')], default='UNALIGNED', max_length=50),
        ),
        migrations.AlterField(
            model_name='sequencedataset',
            name='reference_genome',
            field=models.CharField(choices=[('HG19', 'Human Genome 19'), ('HG18', 'Human Genome 18'), ('MM10', 'Mouse Genome 10'), ('UNALIGNED', 'Not aligned to a reference'), ('UNUSABLE', 'Alignments are not usable')], default='UNALIGNED', max_length=50),
        ),
    ]
