# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-01 18:57
from __future__ import unicode_literals

from django.db import migrations


def rename_ref_genome(apps, schema_editor):
    SequenceDataset = apps.get_model('tantalus', 'SequenceDataset')
    for dataset in SequenceDataset.objects.filter():
        if dataset.reference_genome == 'hg19':
            dataset.reference_genome = 'HG19'
        if dataset.reference_genome == 'grch37':
            dataset.reference_genome = 'HG19'
        if dataset.reference_genome == 'mm10':
            dataset.reference_genome = 'MM10'
        dataset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0071_auto_20181101_1856'),
    ]

    operations = [
        migrations.RunPython(rename_ref_genome),
    ]
