# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-20 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0077_auto_20181120_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsequencefileinfo',
            name='genome_region',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sequencefileinfo',
            name='genome_region',
            field=models.TextField(null=True),
        ),
    ]
