# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-21 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0079_auto_20181120_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsequencedataset',
            name='reference_genome',
            field=models.CharField(default='UNALIGNED', max_length=50),
        ),
        migrations.AlterField(
            model_name='sequencedataset',
            name='reference_genome',
            field=models.CharField(default='UNALIGNED', max_length=50),
        ),
    ]
