# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-04 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0080_auto_20181121_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsample',
            old_name='collab_sample_id',
            new_name='external_sample_id',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='collab_sample_id',
            new_name='external_sample_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='coverage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='library_type',
            field=models.CharField(blank=True, choices=[('EXOME', 'Bulk Whole Exome Sequence'), ('WGS', 'Bulk Whole Genome Sequence'), ('RNASEQ', 'Bulk RNA-Seq'), ('SC_WGS', 'Single Cell Whole Genome Sequence'), ('SC_RNASEQ', 'Single Cell RNA-Seq'), ('EXCAP', 'Exon Capture'), ('MIRNA', 'micro RNA'), ('BISULFITE', 'Bisulfite'), ('CHIP', 'Chromatin Immunoprecipitation'), ('MRE', 'Methylation sensitive restriction enzyme sequencing'), ('MEDIP', 'Methylated DNA immunoprecipitation'), ('DNA_AMPLICON', 'Targetted DNA Amplicon Sequence')], default=None, max_length=240, null=True),
        ),
    ]
