# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-30 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def data_migrate(apps, schema_editor):
    seqds = apps.get_model('tantalus','SequenceDataset')
    vocab = apps.get_model('tantalus','ReferenceGenome')

    recs = seqds.objects.values_list('temp',flat=True).distinct()

    print("\n\n%s;\n  N=%i;\n" % (str(recs.query),recs.count()))

    #fill vocabulary, ignore existing values
    for x in recs:
        print(x)
        vocab.objects.get_or_create(reference_genome=x)

    recs = seqds.objects.all()

    #save values in the temporary field
    print("\n\n%s;\n  N=%i;\n" % (str(recs.query),recs.count()))
    for r in recs:
        v = vocab.objects.get(reference_genome=r.temp)
        r.reference_genome=v
        if (0 == (r.id % 113)):
            print("----- %s; %s;" % (r.id,r.reference_genome.id))
        r.save()


def do0(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0081_historicalreferencegenome_referencegenome'),
    ]

    # -- rename "reference_genome" to "temp"
    # -- create FK "reference_genome" (vocabulary)
    # -- fill vocabulary with unique values from "reference_genome"
    # -- set "reference_genome" FK to values based on "temp" and vocabulary
    # -- remove "temp"
    operations = [
        migrations.RenameField(
            model_name='sequencedataset',
            old_name = 'reference_genome',
            new_name = 'temp'
        ),
        migrations.AddField(
            model_name='SequenceDataset',
            name='reference_genome',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE,
                                    to='tantalus.ReferenceGenome'),
        ),
        migrations.RunPython(data_migrate,do0),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='temp'
        ),
    ]
