# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-06 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0081_auto_20181204_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brcfastqimport',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='filetransfer',
            name='from_storage',
        ),
        migrations.RemoveField(
            model_name='filetransfer',
            name='to_storage',
        ),
        migrations.DeleteModel(
            name='GscDlpPairedFastqQuery',
        ),
        migrations.DeleteModel(
            name='GscWgsBamQuery',
        ),
        migrations.RemoveField(
            model_name='importdlpbam',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='md5check',
            name='file_instance',
        ),
        migrations.AlterUniqueTogether(
            name='reservedfileinstance',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='reservedfileinstance',
            name='file_resource',
        ),
        migrations.RemoveField(
            model_name='reservedfileinstance',
            name='file_transfer',
        ),
        migrations.RemoveField(
            model_name='reservedfileinstance',
            name='to_storage',
        ),
        migrations.DeleteModel(
            name='BRCFastqImport',
        ),
        migrations.DeleteModel(
            name='FileTransfer',
        ),
        migrations.DeleteModel(
            name='ImportDlpBam',
        ),
        migrations.DeleteModel(
            name='MD5Check',
        ),
        migrations.DeleteModel(
            name='ReservedFileInstance',
        ),
    ]
