# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-06 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0082_auto_20181206_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalserverstorage',
            name='queue_prefix',
        ),
        migrations.RemoveField(
            model_name='serverstorage',
            name='queue_prefix',
        ),
    ]
