# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-05 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


aligner_choices = (
    ('BWA_MEM_0_7_6A', 'BWA-mem 0.7.6a'),
    ('BWA_ALN_0_5_7', 'BWA 0.5.7 Alignment'),
    ('NOVO_3_01_01', 'Novoalign 3.01.01'),
    ('NOVO_3_02_10', 'Novoalign 3.02.10'),
    ('NOVO_3_04_06', 'Novoalign 3.04.06'),
    ('BISMARK_0_7_6', 'Bismark 0.7.6 Alignment'),
)


def populate_aligner(apps, schema_editor):
    AlignmentTool = apps.get_model('tantalus', 'AlignmentTool')

    for k, v in aligner_choices:
        AlignmentTool.objects.create(name=k, description=v)


aligner_fixup = {
    'nan': None,
    'BWA 0.5.7 Alignment':                                  'BWA_ALN_0_5_7',
    'BWA 0.5.7 Alignment, Novoalign 3.01.01 Alignment':     'BWA_ALN_0_5_7',
    'bwa-aln':                                              'BWA_ALN_0_5_7',
    'bwa_aln':                                              'BWA_ALN_0_5_7',
    'bwa-mem':                                              'BWA_MEM_0_7_6A',
    'BWA-mem 0.7.6a Alignment Sambamba':                    'BWA_MEM_0_7_6A',
    'bwa_mem':                                              'BWA_MEM_0_7_6A',
    'BWA-mem 0.7.6a Alignment':                             'BWA_MEM_0_7_6A',
    'Bismark 0.7.6 Alignment':                              'BISMARK_0_7_6',
    'Novoalign 3.02.10 Alignment':                          'NOVO_3_02_10',
    'Novoalign 3.01.01 Alignment':                          'NOVO_3_01_01',
    'Novoalign 3.04.06 -k17 -s2 Alignment':                 'NOVO_3_04_06',
}


def migrate_aligner(apps, schema_editor):
    SequenceDataset = apps.get_model('tantalus', 'SequenceDataset')
    AlignmentTool = apps.get_model('tantalus', 'AlignmentTool')

    aligners = dict([(l.name, l) for l in AlignmentTool.objects.all()])

    for model in SequenceDataset.objects.all():
        name = model.temp_aligner
        if name in aligner_fixup:
            name = aligner_fixup[name]
        if name is None:
            model.aligner = None
            print '{} -> None'.format(model.temp_aligner)
        else:
            model.aligner = aligners[name]
            print '{} -> {}'.format(model.temp_aligner, model.aligner.name)
        model.save()


#empty function, required to rollback migration
def do0(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0084_patient_case_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAlignmentTool',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical alignment tool',
            },
        ),
        migrations.RunPython(
            populate_aligner,
            do0
        ),
        migrations.RenameField(
            model_name='historicalsequencedataset',
            old_name='aligner',
            new_name='temp_aligner',
        ),
        migrations.RenameField(
            model_name='sequencedataset',
            old_name='aligner',
            new_name='temp_aligner',
        ),
        migrations.AddField(
            model_name='historicalsequencedataset',
            name='aligner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tantalus.AlignmentTool'),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='aligner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tantalus.AlignmentTool'),
        ),
        migrations.RunPython(
            migrate_aligner,
            do0
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='temp_aligner',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='temp_aligner',
        ),
    ]

