# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-20 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0084_patient_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='external_patient_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
