# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-12 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0085_auto_20181208_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsample',
            old_name='collaborator',
            new_name='researcher',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='collaborator',
            new_name='researcher',
        ),
        migrations.AlterField(
            model_name='patient',
            name='external_patient_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
