# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-14 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0086_auto_20181212_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsample',
            old_name='patient_id',
            new_name='SA_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='SA_id',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='patient_id',
            new_name='SA_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='reference_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
