# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-28 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0088_auto_20181220_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinstance',
            name='filename_override',
        ),
        migrations.RemoveField(
            model_name='historicalfileinstance',
            name='filename_override',
        ),
        migrations.AddField(
            model_name='fileinstance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfileinstance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
