# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-28 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0090_auto_20181228_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalazureblobcredentials',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='azureblobstorage',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='historicalazureblobstorage',
            name='credentials',
        ),
        migrations.DeleteModel(
            name='AzureBlobCredentials',
        ),
        migrations.DeleteModel(
            name='HistoricalAzureBlobCredentials',
        ),
    ]
