# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-02 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0091_auto_20181228_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencedataset',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tantalus.Sample'),
        ),
    ]
