# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0092_auto_20190103_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsdataset',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tantalus.Analysis'),
        ),
    ]
