# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-04 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0093_auto_20190103_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencedataset',
            name='aligner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tantalus.AlignmentTool'),
        ),
        migrations.AlterField(
            model_name='sequencedataset',
            name='reference_genome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tantalus.ReferenceGenome'),
        ),
    ]
