# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-04 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0094_auto_20190104_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresultsdataset',
            name='results_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultsdataset',
            name='results_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
