# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-04 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0096_auto_20190104_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analysis_Type',
            new_name='AnalysisType',
        ),
        migrations.RenameModel(
            old_name='HistoricalAnalysis_Type',
            new_name='HistoricalAnalysisType',
        ),
        migrations.AlterModelOptions(
            name='historicalanalysistype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical analysis type'},
        ),
    ]
