# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-07 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0096_auto_20190104_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalserverstorage',
            name='read_only',
        ),
        migrations.RemoveField(
            model_name='serverstorage',
            name='read_only',
        ),
    ]
