# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-21 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0098_auto_20190110_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsdataset',
            name='libraries',
            field=models.ManyToManyField(to='tantalus.DNALibrary'),
        ),
    ]
