# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-21 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0099_resultsdataset_libraries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsample',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
