# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-23 17:31
from __future__ import unicode_literals

from django.db import migrations

from tantalus.models import DNALibrary


class Migration(migrations.Migration):
    def update_result_library_id(apps, schema_editor):
        results = apps.get_model('tantalus', 'ResultsDataset')

        for result in results.objects.all():
            for library in DNALibrary.objects.filter(sequencedataset__id__in=result.analysis.input_datasets.all()):
                result.libraries.add(library.id)

    dependencies = [
        ('tantalus', '0101_sample_id'),
    ]

    operations = [
        migrations.RunPython(update_result_library_id)
    ]
