# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-23 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def update_analysis_type(apps, schema_editor):
        hmmcopy = "hmmcopy"
        align = "align"

        analyses = apps.get_model('tantalus', 'Analysis')
        analysis_type = apps.get_model('tantalus', 'AnalysisType')


        if not analysis_type.objects.filter(name=hmmcopy):
            analysis_type.objects.create(name=hmmcopy)

        if not analysis_type.objects.filter(name=align):
            analysis_type.objects.create(name=align)

        for analysis in analyses.objects.all():
            if hmmcopy in analysis.name:
                analysis.analysis_type = analysis_type.objects.filter(name=hmmcopy)[0]
                analysis.save()
            elif align in analysis.name:
                analysis.analysis_type = analysis_type.objects.filter(name=align)[0]
                analysis.save()
            else:
                pass


    dependencies = [
        ('tantalus', '0102_auto_20190123_1731'),
    ]

    operations = [
        migrations.RunPython(update_analysis_type)
    ]
