# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-26 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0103_auto_20190123_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfiletype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='fileresource',
            name='compression',
        ),
        migrations.RemoveField(
            model_name='fileresource',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='compression',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='file_type',
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.DeleteModel(
            name='HistoricalFileType',
        ),
    ]
