# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-31 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0104_auto_20190131_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfileresource',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
