# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-04 01:36
from __future__ import unicode_literals

from django.db import migrations, models


def update_file_type(apps, schema_editor):
    FileType = apps.get_model('tantalus', 'FileType')
    i = 0
    for t in FileType.objects.all():
        f = t.fileresource_set.all()
        name = t.name
        if len(name) > 50:
            name = ''
        f.update(file_type=name)
        i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0104_auto_20190131_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileresource',
            old_name='file_type',
            new_name='file_type_old',
        ),
        migrations.RenameField(
            model_name='historicalfileresource',
            old_name='file_type',
            new_name='file_type_old',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalfileresource',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(update_file_type),
        migrations.RemoveField(
            model_name='fileresource',
            name='file_type_old',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='file_type_old',
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.RemoveField(
            model_name='historicalfiletype',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalFileType',
        ),
    ]
