# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-31 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0105_auto_20190130_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='temp_result',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='temp_sequence',
        ),
        migrations.RemoveField(
            model_name='Dataset',
            name='previous_dataset_id',
        ),
        migrations.RemoveField(
            model_name='historicalresultsdataset',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='historicalresultsdataset',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalresultsdataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='aligner',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='library',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='reference_genome',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='file_resources',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='aligner',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='file_resources',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='library',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='reference_genome',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='sequence_lanes',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='tags',
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='dataset_class',
            field=models.CharField(choices=[('Sequence', 'Sequence'), ('Results', 'Results')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalResultsDataset',
        ),
        migrations.DeleteModel(
            name='HistoricalSequenceDataset',
        ),
        migrations.DeleteModel(
            name='ResultsDataset',
        ),
        migrations.DeleteModel(
            name='SequenceDataset',
        ),
    ]
