# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-02 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0105_auto_20190201_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalresultsdataset',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='historicalresultsdataset',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalresultsdataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='aligner',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='library',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='reference_genome',
        ),
        migrations.RemoveField(
            model_name='historicalsequencedataset',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='file_resources',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='resultsdataset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='aligner',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='file_resources',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='library',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='reference_genome',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='sequence_lanes',
        ),
        migrations.RemoveField(
            model_name='sequencedataset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='input_datasets',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='input_results',
        ),
        migrations.DeleteModel(
            name='HistoricalResultsDataset',
        ),
        migrations.DeleteModel(
            name='HistoricalSequenceDataset',
        ),
        migrations.DeleteModel(
            name='ResultsDataset',
        ),
        migrations.DeleteModel(
            name='SequenceDataset',
        ),
    ]
