# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-05 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0105_auto_20190204_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresultsdataset',
            name='is_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsequencedataset',
            name='is_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultsdataset',
            name='is_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='is_production',
            field=models.BooleanField(default=False),
        ),
    ]
