# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0107_auto_20190206_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='is_reference',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_reference',
            field=models.NullBooleanField(default=None),
        ),
    ]
