# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0109_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnalibrary',
            name='index_format',
            field=models.CharField(choices=[('S', 'Single Index'), ('D', 'Dual Index (i7 and i5)'), ('TENX', 'Tenx Indexing'), ('N', 'No Indexing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldnalibrary',
            name='index_format',
            field=models.CharField(choices=[('S', 'Single Index'), ('D', 'Dual Index (i7 and i5)'), ('TENX', 'Tenx Indexing'), ('N', 'No Indexing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsequencedataset',
            name='dataset_type',
            field=models.CharField(choices=[('BAM', 'BAM Files'), ('FQ', 'FastQ Files'), ('BCL', 'BCL Files')], default='BAM', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsequencinglane',
            name='read_type',
            field=models.CharField(choices=[('P', 'Paired end tags'), ('S', 'Single end tags'), ('TENX', 'Tenx')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sequencedataset',
            name='dataset_type',
            field=models.CharField(choices=[('BAM', 'BAM Files'), ('FQ', 'FastQ Files'), ('BCL', 'BCL Files')], default='BAM', max_length=50),
        ),
        migrations.AlterField(
            model_name='sequencinglane',
            name='read_type',
            field=models.CharField(choices=[('P', 'Paired end tags'), ('S', 'Single end tags'), ('TENX', 'Tenx')], max_length=50),
        ),
    ]
