# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0110_auto_20190220_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsample',
            old_name='collaborator',
            new_name='researcher',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='collaborator',
            new_name='researcher',
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='reference_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='reference_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
