# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-12 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0111_auto_20190221_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresource',
            name='compression',
        ),
        migrations.RemoveField(
            model_name='fileresource',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='compression',
        ),
        migrations.RemoveField(
            model_name='historicalfileresource',
            name='file_type',
        ),
    ]
