# Generated by Django 2.2 on 2019-04-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0113_auto_20190330_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azureblobstorage',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='serverstorage',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'base_manager_name': 'objects'},
        ),
    ]
