# Generated by Django 2.2 on 2019-04-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0115_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='associate_azure_key',
            new_name='azure_key_associated',
        ),
    ]
