# Generated by Django 2.2.3 on 2019-07-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0117_auto_20190612_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
