# Generated by Django 2.2 on 2019-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0118_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsequencedataset',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
