# Generated by Django 2.2 on 2019-08-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0120_auto_20190820_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsequencedataset',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sequencedataset',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='sequencedataset',
            unique_together={('name', 'version_number')},
        ),
    ]
