# Generated by Django 2.2 on 2019-08-21 20:04

from django.db import migrations


def update_version_number(apps, schema_editor):
    SequenceDataset = apps.get_model('tantalus', 'SequenceDataset')

    for dataset in SequenceDataset.objects.filter(name__contains='_V'):
        if dataset.name.endswith('_V1'):
            dataset.name = dataset.name[:-3]
        elif dataset.name.endswith('_V2'):
            dataset.name = dataset.name[:-3]
        elif dataset.name.endswith('_V3'):
            dataset.name = dataset.name[:-3]
        if SequenceDataset.objects.filter(name=dataset.name).count() > 0:
            dataset.version_number = max([a.version_number for a in SequenceDataset.objects.filter(name=dataset.name)]) + 1
        dataset.save()

    for dataset in SequenceDataset.objects.filter(name__contains='-V'):
        if dataset.name.endswith('-V1'):
            dataset.name = dataset.name[:-3]
        elif dataset.name.endswith('-V2'):
            dataset.name = dataset.name[:-3]
        elif dataset.name.endswith('-V3'):
            dataset.name = dataset.name[:-3]
        if SequenceDataset.objects.filter(name=dataset.name).count() > 0:
            dataset.version_number = max([a.version_number for a in SequenceDataset.objects.filter(name=dataset.name)]) + 1
        dataset.save()

    for dataset in SequenceDataset.objects.filter(name__contains='V'):
        if dataset.name.endswith('HG19'):
            continue
        if dataset.name.endswith('HG18'):
            continue
        if dataset.name.startswith('FQ') and dataset.name[-2] == ('_') and dataset.name[-1] in [str(a) for a in range(10)]:
            continue
        if dataset.name.endswith(')'):
            continue
        raise ValueError('unexpected bam name {dataset.name}')


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0121_auto_20190820_2322'),
    ]

    operations = [
        migrations.RunPython(update_version_number)
    ]
