# Generated by Django 2.2 on 2019-10-30 21:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tantalus', '0123_awss3storage_historicalawss3storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='v1.0.0', max_length=200, validators=[django.core.validators.RegexValidator(message=' must be in "v<MAJOR>.<MINOR>.<PATCH>"; for example, "v0.0.1"', regex='v\\d+\\.\\d+\\.\\d+')])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCurationDataset',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.CharField(default='v1.0.0', max_length=200, validators=[django.core.validators.RegexValidator(message=' must be in "v<MAJOR>.<MINOR>.<PATCH>"; for example, "v0.0.1"', regex='v\\d+\\.\\d+\\.\\d+')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('curation_instance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tantalus.Curation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sequencedataset_instance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tantalus.SequenceDataset')),
            ],
            options={
                'verbose_name': 'historical curation dataset',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCuration',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('version', models.CharField(default='v1.0.0', max_length=200, validators=[django.core.validators.RegexValidator(message=' must be in "v<MAJOR>.<MINOR>.<PATCH>"; for example, "v0.0.1"', regex='v\\d+\\.\\d+\\.\\d+')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical curation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CurationDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v1.0.0', max_length=200, validators=[django.core.validators.RegexValidator(message=' must be in "v<MAJOR>.<MINOR>.<PATCH>"; for example, "v0.0.1"', regex='v\\d+\\.\\d+\\.\\d+')])),
                ('curation_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tantalus.Curation')),
                ('sequencedataset_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tantalus.SequenceDataset')),
            ],
        ),
        migrations.AddField(
            model_name='curation',
            name='sequencedatasets',
            field=models.ManyToManyField(blank=True, through='tantalus.CurationDataset', to='tantalus.SequenceDataset'),
        ),
        migrations.AddField(
            model_name='curation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
