# Generated by Django 2.2 on 2019-11-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0124_auto_20191030_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsequencedataset',
            name='region_split_length',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sequencedataset',
            name='region_split_length',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
