# Generated by Django 2.2 on 2019-10-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0124_curation_curationhistory_historicalcuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencedataset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sequencedataset', to='tantalus.Tag'),
        ),
    ]
