# Generated by Django 2.2 on 2019-10-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0125_auto_20191003_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationhistory',
            name='curation_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.Curation'),
        ),
        migrations.AlterField(
            model_name='sequencedataset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tantalus.Tag'),
        ),
    ]
