# Generated by Django 2.2 on 2020-01-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0125_auto_20191114_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsequencinglane',
            name='sequencing_centre',
            field=models.CharField(choices=[('GSC', 'Genome Science Centre'), ('BRC', 'Biomedical Research Centre'), ('IGO', 'IGO MSKCC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sequencinglane',
            name='sequencing_centre',
            field=models.CharField(choices=[('GSC', 'Genome Science Centre'), ('BRC', 'Biomedical Research Centre'), ('IGO', 'IGO MSKCC')], max_length=50),
        ),
    ]
