# Generated by Django 2.2 on 2020-01-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0126_auto_20200109_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsdataset',
            name='file_resources',
            field=models.ManyToManyField(blank=True, to='tantalus.FileResource'),
        ),
    ]
